### ISSUE TITLE
Incorrect indices being generated

### ISSUE THREAD

**Issue by smrey** [AWGL/NGS_Sample_Sheets#1]
E index is incorrectly assigned for the TruSight One sample sheets. This needs to be updated to match the indices of a known good run (ask tech team for guidance if needed).

**Comment by erikwaskiewicz** [comment]
Indexes for TSO are hard-coded into template in Y:\samplesheet-templates\TrusightOne. Indexes were changed to new ones supplied by Hazel, just waiting on the tech team to confirm that changes are okay.
